// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace Kritikos.Sphinx.Data.Persistence.Migrations
{
    public partial class Breakscirculardependency : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Datasets_StimulusGroups_PrimaryGroupId",
                table: "Datasets");

            migrationBuilder.DropIndex(
                name: "IX_Datasets_PrimaryGroupId",
                table: "Datasets");

            migrationBuilder.DropColumn(
                name: "PrimaryGroupId",
                table: "Datasets");

            migrationBuilder.AddColumn<bool>(
                name: "IsPrimary",
                table: "StimulusGroups",
                type: "boolean",
                nullable: false,
                defaultValue: false);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsPrimary",
                table: "StimulusGroups");

            migrationBuilder.AddColumn<long>(
                name: "PrimaryGroupId",
                table: "Datasets",
                type: "bigint",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Datasets_PrimaryGroupId",
                table: "Datasets",
                column: "PrimaryGroupId");

            migrationBuilder.AddForeignKey(
                name: "FK_Datasets_StimulusGroups_PrimaryGroupId",
                table: "Datasets",
                column: "PrimaryGroupId",
                principalTable: "StimulusGroups",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
