// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace Kritikos.Sphinx.Data.Persistence.Migrations.Sphinx
{
    public partial class Addssignificantstimulimatches : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_SignificantMatch_Stimuli_PrimaryStimulusId",
                table: "SignificantMatch");

            migrationBuilder.DropForeignKey(
                name: "FK_SignificantMatch_Stimuli_SecondaryStimulusId",
                table: "SignificantMatch");

            migrationBuilder.DropPrimaryKey(
                name: "PK_SignificantMatch",
                table: "SignificantMatch");

            migrationBuilder.RenameTable(
                name: "SignificantMatch",
                newName: "SignificantMatches");

            migrationBuilder.RenameIndex(
                name: "IX_SignificantMatch_SecondaryStimulusId",
                table: "SignificantMatches",
                newName: "IX_SignificantMatches_SecondaryStimulusId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_SignificantMatches",
                table: "SignificantMatches",
                columns: new[] { "PrimaryStimulusId", "SecondaryStimulusId" });

            migrationBuilder.AddForeignKey(
                name: "FK_SignificantMatches_Stimuli_PrimaryStimulusId",
                table: "SignificantMatches",
                column: "PrimaryStimulusId",
                principalTable: "Stimuli",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_SignificantMatches_Stimuli_SecondaryStimulusId",
                table: "SignificantMatches",
                column: "SecondaryStimulusId",
                principalTable: "Stimuli",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_SignificantMatches_Stimuli_PrimaryStimulusId",
                table: "SignificantMatches");

            migrationBuilder.DropForeignKey(
                name: "FK_SignificantMatches_Stimuli_SecondaryStimulusId",
                table: "SignificantMatches");

            migrationBuilder.DropPrimaryKey(
                name: "PK_SignificantMatches",
                table: "SignificantMatches");

            migrationBuilder.RenameTable(
                name: "SignificantMatches",
                newName: "SignificantMatch");

            migrationBuilder.RenameIndex(
                name: "IX_SignificantMatches_SecondaryStimulusId",
                table: "SignificantMatch",
                newName: "IX_SignificantMatch_SecondaryStimulusId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_SignificantMatch",
                table: "SignificantMatch",
                columns: new[] { "PrimaryStimulusId", "SecondaryStimulusId" });

            migrationBuilder.AddForeignKey(
                name: "FK_SignificantMatch_Stimuli_PrimaryStimulusId",
                table: "SignificantMatch",
                column: "PrimaryStimulusId",
                principalTable: "Stimuli",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_SignificantMatch_Stimuli_SecondaryStimulusId",
                table: "SignificantMatch",
                column: "SecondaryStimulusId",
                principalTable: "Stimuli",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
