parameters:
- name: environment
  type: string
- name: jobName
  type: string
  default: production
- name: subscription
  type: string
- name: resourceGroup
  type: string
- name: webApp
  type: string
- name: slotName
  type: string
- name: deployToSlot
  type: boolean
  default: false
- name: artifact
  type: string
- name: packagesToPush
  type: string
  default: '*.zip'

stages:
- stage: Deploy
  displayName: Deploys nugets
  dependsOn:
    - Build
    - Test
  jobs:
  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
     - template: azure-job.yml
       parameters:
        jobName: ${{ parameters.slotName }}
        environment: ${{ parameters.environment }}
        subscription: ${{ parameters.subscription }}
        resourceGroup: ${{ parameters.resourceGroup }}
        webApp: ${{ parameters.webApp }}
        slotName: ${{ parameters.slotName }}
        deployToSlot: ${{ parameters.deployToSlot }}
        artifact: ${{ parameters.artifact }}
        packagesToPush: ${{ parameters.packagesToPush }}
